### ISSUE TITLE
Copyright infrigment

### ISSUE THREAD

**Issue by ghost** [OVAWARE/Plixel#1]
None of the mods whose resources are used are credited. This is, among violating other licenses (MIT, LGPL-3, and 2 custom licenses), a GPL-3 violation — Better Nether is GPL-3 [(source)](https://github.com/paulevsGitch/BetterNether/blob/master/LICENSE). In order for this project to be able to use Better Nether assets, the entire repo _has_ to be GPL-3. Please consider resolving this licensing issue.

(This probably also infringes on Mojang's copyright and violates their EULA but I can't say that for certain)

**Comment by ghost** [comment]
Update: This breaks Botania's license too [(source)](https://github.com/VazkiiMods/Botania/blob/1.20.x/LICENSE.txt) since there's no attribution given.

**Comment by OVAWARE** [comment]
Removed reuploaded images from the github and reset push history.
